module Dataleon
  module Models
    type individual_delete_params =
      { individual_id: String } & Dataleon::Internal::Type::request_parameters

    class IndividualDeleteParams < Dataleon::Internal::Type::BaseModel
      extend Dataleon::Internal::Type::RequestParameters::Converter
      include Dataleon::Internal::Type::RequestParameters

      attr_accessor individual_id: String

      def initialize: (
        individual_id: String,
        ?request_options: Dataleon::request_opts
      ) -> void

      def to_hash: -> {
        individual_id: String,
        request_options: Dataleon::RequestOptions
      }
    end
  end
end
