module Dataleon
  class Check = Dataleon::Models::Check

  class CompanyCreateParams = Dataleon::Models::CompanyCreateParams

  class CompanyListParams = Dataleon::Models::CompanyListParams

  class CompanyRegistration = Dataleon::Models::CompanyRegistration

  class Individual = Dataleon::Models::Individual

  class IndividualCreateParams = Dataleon::Models::IndividualCreateParams

  class IndividualListParams = Dataleon::Models::IndividualListParams

  module Individuals = Dataleon::Models::Individuals
end
