module Dataleon
  module Resources
    class Companies
      attr_reader documents: Dataleon::Resources::Companies::Documents

      def create: (
        company: Dataleon::CompanyCreateParams::Company,
        workspace_id: String,
        ?source_id: String,
        ?technical_data: Dataleon::CompanyCreateParams::TechnicalData,
        ?request_options: Dataleon::request_opts
      ) -> Dataleon::CompanyRegistration

      def list: (
        ?end_date: Date,
        ?limit: Integer,
        ?offset: Integer,
        ?source_id: String,
        ?start_date: Date,
        ?state: Dataleon::Models::CompanyListParams::state,
        ?status: Dataleon::Models::CompanyListParams::status,
        ?workspace_id: String,
        ?request_options: Dataleon::request_opts
      ) -> Dataleon::Models::company_list_response

      def initialize: (client: Dataleon::Client) -> void
    end
  end
end
