module Dataleon
  module Resources
    class Individuals
      attr_reader documents: Dataleon::Resources::Individuals::Documents

      def create: (
        workspace_id: String,
        ?person: Dataleon::IndividualCreateParams::Person,
        ?source_id: String,
        ?technical_data: Dataleon::IndividualCreateParams::TechnicalData,
        ?request_options: Dataleon::request_opts
      ) -> Dataleon::Individual

      def list: (
        ?end_date: Date,
        ?limit: Integer,
        ?offset: Integer,
        ?source_id: String,
        ?start_date: Date,
        ?state: Dataleon::Models::IndividualListParams::state,
        ?status: Dataleon::Models::IndividualListParams::status,
        ?workspace_id: String,
        ?request_options: Dataleon::request_opts
      ) -> Dataleon::Models::individual_list_response

      def initialize: (client: Dataleon::Client) -> void
    end
  end
end
