module Dataleon
  module Models
    module Companies
      type document_list_params =
        {  } & Dataleon::Internal::Type::request_parameters

      class DocumentListParams < Dataleon::Internal::Type::BaseModel
        extend Dataleon::Internal::Type::RequestParameters::Converter
        include Dataleon::Internal::Type::RequestParameters

        def initialize: (?request_options: Dataleon::request_opts) -> void

        def to_hash: -> { request_options: Dataleon::RequestOptions }
      end
    end
  end
end
