module Dataleon
  module Models
    module Companies
      type document_upload_params =
        {
          document_type: Dataleon::Models::Companies::DocumentUploadParams::document_type,
          file: Dataleon::Internal::file_input,
          url: String
        }
        & Dataleon::Internal::Type::request_parameters

      class DocumentUploadParams < Dataleon::Internal::Type::BaseModel
        extend Dataleon::Internal::Type::RequestParameters::Converter
        include Dataleon::Internal::Type::RequestParameters

        attr_accessor document_type: Dataleon::Models::Companies::DocumentUploadParams::document_type

        attr_reader file: Dataleon::Internal::file_input?

        def file=: (
          Dataleon::Internal::file_input
        ) -> Dataleon::Internal::file_input

        attr_reader url: String?

        def url=: (String) -> String

        def initialize: (
          document_type: Dataleon::Models::Companies::DocumentUploadParams::document_type,
          ?file: Dataleon::Internal::file_input,
          ?url: String,
          ?request_options: Dataleon::request_opts
        ) -> void

        def to_hash: -> {
          document_type: Dataleon::Models::Companies::DocumentUploadParams::document_type,
          file: Dataleon::Internal::file_input,
          url: String,
          request_options: Dataleon::RequestOptions
        }

        type document_type =
          :bank_statements
          | :liasse_fiscale
          | :amortised_loan_schedule
          | :accounting
          | :invoice
          | :receipt
          | :company_statuts
          | :kbis
          | :rib
          | :carte_grise
          | :proof_address
          | :identity_document

        module DocumentType
          extend Dataleon::Internal::Type::Enum

          BANK_STATEMENTS: :bank_statements
          LIASSE_FISCALE: :liasse_fiscale
          AMORTISED_LOAN_SCHEDULE: :amortised_loan_schedule
          ACCOUNTING: :accounting
          INVOICE: :invoice
          RECEIPT: :receipt
          COMPANY_STATUTS: :company_statuts
          KBIS: :kbis
          RIB: :rib
          CARTE_GRISE: :carte_grise
          PROOF_ADDRESS: :proof_address
          IDENTITY_DOCUMENT: :identity_document

          def self?.values: -> ::Array[Dataleon::Models::Companies::DocumentUploadParams::document_type]
        end
      end
    end
  end
end
